### PR TITLE
:triangular_flag_on_post: DOP-4060 adds new featrue flag to the docs-worker-pool

### PR DESCRIPTION
**Pull request by caesarbell**
This PR introduces the new feature flag for hiding the locale on the unified footer on the docs page in production and showing it for non-product environments.

### CODE REVIEW

**Review by seungpark — APPROVED** [review]
this LGTM. on a minor note, seems like this env flag is set to false? `/env/legacy/docs/worker_pool/flag/hide_locale` not sure if we want to show the locale selection for legacy

**Comment by caesarbell** [comment]
> this LGTM. on a minor note, seems like this env flag is set to false? `/env/legacy/docs/worker_pool/flag/hide_locale` not sure if we want to show the locale selection for legacy

@seungpark I can change this. Legacy is a non-production env correct?

**Review by branberry — APPROVED** [review]
LGTM!

**Comment by schmalliso** [comment]
> > this LGTM. on a minor note, seems like this env flag is set to false? `/env/legacy/docs/worker_pool/flag/hide_locale` not sure if we want to show the locale selection for legacy
> 
> @seungpark I can change this. Legacy is a non-production env correct?

It is, but it also probably doesn't matter since (a) the Legacy environment doesn't work and (b) doesn't build with the consistent nav.

**Pull request merged**
